language: python
python:
  - "2.6"
  - "2.7"
notifications:
  email:
   - henry.s.huang@gmail.com
install:
 # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install make libaugeas-dev libxml2-dev
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - pip install --use-mirrors -r requirements.txt
  - python setup.py develop
script:
  - python test/augeas/test_augeas.py
  - nosetests test
